* dotfiles ┐【￣～￣】┌
These are my personal dotfiles.
I'm using:
 - [[https://www.gnu.org/software/emacs/][GNU Emacs]]
 - [[https://www.gnu.org/software/stow][GNU stow]]
 - [[https://github.com/Airblader/i3][i3-gaps]]
 - [[https://github.com/jaagr/polybar][Polybar]]
 - [[https://github.com/nana-4/materia-theme][Materia Theme]]
 - [[http://zsh.sourceforge.net][zsh]]

** TODOS:

 1) Making an own [[https://github.com/brndnmtthws/conky/wiki/Configuraion-Settings][conky]], conky_maia-like

** Getting Started
*** Prerequisites
**** Pacman Install
***** System
      - lightdm
****** Terminal 
       - zsh
       - termite
***** Essentials
      - nyancat
      - stow
      - git
      - python-pip
      - xsel
      - rofi
***** Lifestyle
      - emacs
      - texlive-most
      - evince
      - scrot
      - aspell-en
***** Pretty stuff (i.e. ricing, pretty cli-apps)
      - cmus
      - lxappearance
      - conky
      - arc-icon-theme
****** oh-my-zsh
       - powerline-fonts
       - awesome-terminal-fonts
       - zsh-theme-powerlevel9k

**** Yaourt Install
***** System
      - lightdm-mini-greeter
      - i3-gaps (Moved into the official Arch community repo)
      - i3lock-color
***** Essentials
      - polybar
***** Pretty stuff (i.e. ricing, pretty cli-apps)
      - cava
      - materia-theme
      - neofetch
*** Setting up zsh
#+BEGIN_SRC sh
chsh -s /bin/zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"  # Downloading/Installing oh-my-zsh
cp -r /usr/share/zsh-theme-powerlevel9k ~/.oh-my-zsh/themes/powerlevel9k  # copying powerlevel9k-theme to the desired directory
rm -rf ~/.*bash* # remove bash related files from your home directory.. don't do it if you wanna keep using bash with this user
#+END_SRC

*** Setting up Emacs
I tried to make this as easy as possible. All packages should be installed automatically.
Config file is =.emacs.d/config.org=
*** Font setup
Stolen from [[https://github.com/powerline/fonts][here]].
#+BEGIN_SRC sh
git clone # clone
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts
#+END_SRC

*** "Installing" the dotfiles.
Take a look at already existing files and delete them if necessary.
#+BEGIN_SRC sh
git clone https://github.com/TuDatTr/dotfiles .dotfiles && cd .dotfiles
stow emacs
stow zsh
stow config
sudo ln -s ~/.scripts/pipes.sh /usr/local/bin/pipes
#+END_SRC


* Author
 - Tuan-Dat Tran - [[https://github.com/tudattr/][TuDatTr]]

* License
This project is license under the GPL-3.0 License - see LICENSE file for details.

* Acknowledgements
 - [[https://www.reddit.com/r/unixporn/][unixporn - the home for *NIX customisation!]]
 - [[https://uigradients.com][uiGradients - Beautiful colored gradients]]
 - [[http://terminal.sexy/][terminal.sexy - Terminal Color Scheme Designer]]
